nohup python3 -m jssp.train\
    -clip_range 0.20\
    --custom_heuristic_names SPT MWKR MOPNR FDD/MWKR\
    --device cpu\
    --duration_type deterministic\
    --ent_coef 0.01\
    --exp_name_appendix QUICKSTART_RUN\
    --fe_type dgl\
    --fixed_validation\
    --gae_lambda 0.99\
    --graph_has_relu\
    --graph_pooling max\
    --hidden_dim_actor 32\
    --hidden_dim_critic 32\
    --hidden_dim_features_extractor 64\
    --layer_pooling last\
    --max_n_j 100\
    --max_n_m 20\
    --mlp_act gelu\
    --n_j 30\
    --n_layers_features_extractor 2\
    --n_m 20\
    --n_mlp_layers_actor 2\
    --n_mlp_layers_critic 2\
    --n_mlp_layers_features_extractor 2\
    --n_validation_env 100\
    --n_workers 1\
    --n_steps_episode 1000\
    --optimizer adamw\
    --ortools_strategy realistic\
    --seed 0\
    --target_kl 0.04\
    --total_timesteps 1_000_000\
    --validation_freq 3\
    --vf_coef 1.0\
    --gconv_type gin\
    --reward_model_config L2D\
    --graph_pooling avg\
    --disable_visdom > training_log.txt 2>&1 &
